version: '3.9'

services:
  db:
    image: postgres:13-alpine
    volumes:
      # - pg_data:/var/lib/postgresql/data/
      # - ./dump.sql:/docker-entrypoint-initdb.d/dummy_dump.sql
      - ./database.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    expose:
      - 5432
    networks:
     - web
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=NenadoTak1987
      - POSTGRES_DB=donut

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=NenadoTak1987
      - DB_NAME=donut
      - WALLET_KEY=key
      - CONTRACT_API_KEY=key
      - CONTRACT_ADDRESS=0xE15B011f681632AFcC7F4a732D4b356da0fAC86A
      - GOOGLE_APPLICATION_CREDENTIALS=serviceaccount.json
    depends_on:
      - db
    networks:
     - web
    volumes:
      - ./backend/uploads:/backend/uploads/
      - ./backend/assets:/backend/assets/
      - ./backend/src/modules/badWords:/backend/src/modules/badWords

  sockets:
    build: ./sockets
    ports:
      - "4005:4005"
    environment:
      - PORT=4005
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=NenadoTak1987
      - DB_NAME=donut
    depends_on:
      - db
    networks:
     - web

  nginx:
    build: ./nginx
    depends_on:
      - backend
      - sockets
    ports:
      - "8000:8000"
    networks:
     - web

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_PORT=5000
        - NODE_ENV=production
        - WALLET=metamask
        - STORAGE_TOKEN=token
        - GOOGLE_API_KEY=key
    depends_on:
      - backend
      - sockets
    networks:
      - web
    ports:
      - "8095:80"

networks:
  web:
    external: true

volumes:
  pg_data: