name: Deploy prod

on:
  push:
    branches: [production]
    paths-ignore:
      - ".github/workflows/*"
  workflow_dispatch:

jobs:
  deploy_and_build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Run update script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASS }}
          script: bash ~/donut/update.sh
          script_stop: true
